### GET запрос получения всех аккаунтов
GET http://localhost:8061/api/account

### DELETE запрос для удаления аккаунта
DELETE http://localhost:8061/api/account/delete/
Content-Type: application/json

{
  "firstName": "Anry",
  "lastName": "Solovev",
  "email": "unsupportedemail.solo@example.com",
  "password": "password456",
  "phoneNumber": "+1234567890",
  "dateOfBirth": "1965-12-02",
  "accountBalance": 230000000000.00,
  "active": true,
  "accountRating": 4.5,
  "accountType": "PREMIUM"
}

### POST запрос для создания аккаунта
POST http://localhost:8061/api/account/open
Content-Type: application/json

{
  "firstName": "Lyudmila",
  "lastName": "Putina",
  "email": "lyuda.crusher99@yandex.corum",
  "password": "parolParol777",
  "phoneNumber": "+7911111111",
  "dateOfBirth": "1985-12-11",
  "accountBalance": 45000000.00,
  "active": true,
  "accountRating": 5.0,
  "accountType": "PREMIUM"
}
